### ISSUE TITLE
貌似还没有提交到maven中央仓库？

### ISSUE THREAD

**Issue by shevawen** [ofpay/dubbo-rpc-jsonrpc#1]
RT.

**Comment by JoeCao** [comment]
正在提交，需要两个工作日

**Comment by JoeCao** [comment]
已经提交到了中央仓库
<dependency>
    <groupId>com.ofpay</groupId>
    <artifactId>dubbo-rpc-jsonrpc</artifactId>
    <version>1.0.1</version>
</dependency>

**Comment by shevawen** [comment]
:thumbsup:
